/* en.js */
var msg = {
    Grupo: "Group:",
    Error: "Error:",
    Uno_de: "One of:",
    Ninguno_de: "None of:",
    Inicio_de_Linea: "Start of Line",
    "Final de linea": "End of Line",
    "Cualquier carácter": "Any character",
    Digito: "Digit",
    Repeticiones: "times",
    Referencia: "Back reference (group =",
    match: "Match",
    valor: "Value",
    resultadoMacht: "Empty Macht.",
    "No digito": "No digit",
    "Tabulador Vertical": "Vertical Tab",
    "Caracter Alfanumerico": "word",
    "No Caracter Alfanumerico": "No word",
    "Espacio en Blanco": "White space",
    "No Espacio en Blanco": "Non white space",
    "No Limite de Palabra": "Non word boundary",
    "Limite de Palabra": "Word boundary",
    "tabulador": "Tab",
    "Nueva linea": "New line",
    "Salto de página": "Form feed",
    "Retorno de carro": "Carriage return",
    use: "Use this expression: ",
    "Expresión Vacía": "Empty Expresion",
    server: "Server Error",
    GrupoNegativo: "Negative Lookahead"
};