/* es.js */
var msg = {
    Grupo: "Grupo:",
    Error: "Error:",
    Uno_de: "Uno de:",
    Ninguno_de: "Ninguno de:",
    'Inicio de Linea': "Inicio de Linea",
    "Final de linea": "Final de linea",
    "Cualquier carácter":"Cualquier carácter",
    Digito: "Digito",
    Repeticiones: "veces",
    Referencia: "Referencia de Grupo (grupo = ",
    match: "Ocurrencia",
    valor: "Valor",
    resultadoMacht: "No hay resultado de Ocurrencia.",
    "No digito": "No digito",
    "Tabulador Vertical": "Tabulador Vertical",
    "Caracter Alfanumerico": "Carácter Alfanumérico",
    "No Caracter Alfanumerico": "No Caracter Alfanumerico",
    "Espacio en Blanco": "Espacio en Blanco",
    "No Espacio en Blanco": "No Espacio en Blanco",
    "No Limite de Palabra": "No Limite de Palabra",
    "Limite de Palabra": "Limite de Palabra",
    "tabulador": "Tabulador",
    "Nueva linea": "Nueva linea",
    "Salto de página": "Salto de página",
    "Retorno de carro": "Retorno de carro",
    use: "Use la expresión siguiente: ",
    "Expresión Vacía": "Expresión Vacía",
    server: "Error en el Servidor",
    GrupoNegativo: "Negación Adelantada"
};